import type { EquipmentName, EquipmentProduct } from "@/types/equipmentSelection";

export { NONE_PRODUCT_ID } from "@/types/equipmentSelection";

/**
 * 설비 선택 페이지 전용 임시(목업) 데이터입니다.
 * 실제 제품 카탈로그/DB가 연동되기 전까지 사용하는 더미 데이터이며,
 * 실제 제품 정보와 무관합니다.
 *
 * 실제 제품으로 교체하려면 아래 EQUIPMENT_PRODUCTS의 각 항목에서:
 * - name, description: 실제 제품명/설명으로 바로 수정
 * - price: 원 단위 숫자로 입력 (예: 45000). 미정이면 null 유지
 * - image: 사진 파일을 frontend/public/images/equipment/ 에 넣고
 *          "/images/equipment/파일명.jpg" 형태의 경로를 입력 (없으면 null)
 * - abilityUnit: 다른 기능이 참조할 제품별 고유 정수 값 (예: 소화기 능력단위).
 *                설비마다 의미가 다를 수 있음. 미정이면 null 유지
 */
export const IS_MOCK_EQUIPMENT_DATA = true;

export const EQUIPMENT_LIST: EquipmentName[] = [
  "소화기",
  "스프링클러",
  "차동식열감지기",
  "정온식열감지기",
  "연기감지기",
  "비상구유도등",
  "복도통로유도등",
  "거실통로유도등",
  "계단통로유도등",
  "댐퍼",
  "발신기",
  "옥내소화전",
  "탬퍼스위치",
  "압력스위치",
  "유수검지스위치",
  "예비펌프",
  "주펌프",
  "충압펌프",
  "급기팬",
  "배기팬",
  "자동폐쇄장치",
];

export const EQUIPMENT_ICONS: Record<EquipmentName, string> = {
  소화기: "🧯",
  스프링클러: "💧",
  차동식열감지기: "🌡️",
  정온식열감지기: "🔥",
  연기감지기: "💨",
  비상구유도등: "🚪",
  복도통로유도등: "🏃",
  거실통로유도등: "🛋️",
  계단통로유도등: "🪜",
  댐퍼: "🌀",
  발신기: "🔔",
  옥내소화전: "🚒",
  탬퍼스위치: "🔒",
  압력스위치: "🎚️",
  유수검지스위치: "💦",
  예비펌프: "🔄",
  주펌프: "⚙️",
  충압펌프: "🚰",
  급기팬: "🌬️",
  배기팬: "🌫️",
  자동폐쇄장치: "🔐",
};

export const EQUIPMENT_PRODUCTS: Record<EquipmentName, EquipmentProduct[]> = {
  소화기: [
    {
      id: "extinguisher-1",
      name: "3.3kg 분말소화기",
      description: "사무실 학교용 가정용 삼우산기 ABC 축압식",
      icon: "🧯",
      price: 27000,
      image: "/images/equipment/extinguisher-1.png",
      abilityUnit: null,
    },
    {
      id: "extinguisher-2",
      name: "CO₂ 소화기",
      description: "전기 및 유류 화재에 적합하며 오염이 적은 이산화탄소 소화기",
      icon: "🧯",
      price: 65000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "extinguisher-3",
      name: "청정 소화기",
      description: "전자 장비 주변 화재에 적합한 할로겐화합물 청정소화기",
      icon: "🧯",
      price: 89000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "extinguisher-4",
      name: "축압식 소화기",
      description: "압력 게이지로 상태 확인이 쉬운 축압식 분말소화기",
      icon: "🧯",
      price: 32000,
      image: null,
      abilityUnit: null,
    },
  ],
  스프링클러: [
    {
      id: "sprinkler-1",
      name: "일반형 스프링클러",
      description: "표준 감열부를 사용하는 범용 자동 소화 설비",
      icon: "💧",
      price: 15000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "sprinkler-2",
      name: "조기반응형 스프링클러",
      description: "화재 초기 단계에서 빠르게 반응하는 조기반응형(ESFR) 헤드",
      icon: "💧",
      price: 42000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "sprinkler-3",
      name: "측벽형 스프링클러",
      description: "벽면에 설치해 좁은 공간에 적합한 측벽형 헤드",
      icon: "💧",
      price: 18000,
      image: null,
      abilityUnit: null,
    },
  ],
  차동식열감지기: [
    {
      id: "heat-differential-1",
      name: "차동식 스팟형 1종",
      description: "온도 상승률을 감지하는 표준형 차동식 감지기",
      icon: "🌡️",
      price: 12000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "heat-differential-2",
      name: "차동식 스팟형 2종",
      description: "일반 사무 공간에 적합한 보급형 차동식 감지기",
      icon: "🌡️",
      price: 9000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "heat-differential-3",
      name: "차동식 분포형",
      description: "넓은 면적을 감지 회로로 연결하는 분포형 차동식 감지기",
      icon: "🌡️",
      price: 35000,
      image: null,
      abilityUnit: null,
    },
  ],
  정온식열감지기: [
    {
      id: "heat-fixed-1",
      name: "정온식 스팟형 특종",
      description: "고온이 발생하는 주방 등에 적합한 특종 정온식 감지기",
      icon: "🔥",
      price: 13000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "heat-fixed-2",
      name: "정온식 스팟형 1종",
      description: "일정 온도 이상에서 작동하는 표준형 정온식 감지기",
      icon: "🔥",
      price: 10000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "heat-fixed-3",
      name: "방수형 정온식 감지기",
      description: "습기가 많은 장소에 적합한 방수형 정온식 감지기",
      icon: "🔥",
      price: 16000,
      image: null,
      abilityUnit: null,
    },
  ],
  연기감지기: [
    {
      id: "smoke-1",
      name: "광전식 스팟형 연기감지기",
      description: "산란광 방식을 사용하는 표준 연기감지기",
      icon: "💨",
      price: 14000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "smoke-2",
      name: "이온화식 연기감지기",
      description: "미세한 연기 입자에도 민감하게 반응하는 이온화식 감지기",
      icon: "💨",
      price: 11000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "smoke-3",
      name: "축적형 연기감지기",
      description: "오작동을 줄이기 위해 신호를 축적해 판단하는 감지기",
      icon: "💨",
      price: 17000,
      image: null,
      abilityUnit: null,
    },
  ],
  비상구유도등: [
    {
      id: "exit-light-1",
      name: "표준형 비상구유도등",
      description: "출입구 상단에 설치하는 기본형 비상구 유도등",
      icon: "🚪",
      price: 45000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exit-light-2",
      name: "축광형 비상구유도등",
      description: "정전 시에도 잔광으로 식별이 가능한 축광형 유도등",
      icon: "🚪",
      price: 38000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exit-light-3",
      name: "매입형 비상구유도등",
      description: "천장이나 벽에 매립해 설치하는 매입형 유도등",
      icon: "🚪",
      price: 62000,
      image: null,
      abilityUnit: null,
    },
  ],
  복도통로유도등: [
    {
      id: "corridor-light-1",
      name: "표준형 복도통로유도등",
      description: "복도 벽면에 설치하는 기본형 통로유도등",
      icon: "🏃",
      price: 40000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "corridor-light-2",
      name: "바닥매입형 복도통로유도등",
      description: "바닥에 매립해 시야를 가리지 않는 통로유도등",
      icon: "🏃",
      price: 55000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "corridor-light-3",
      name: "고휘도 복도통로유도등",
      description: "긴 복도에서도 식별이 쉬운 고휘도 통로유도등",
      icon: "🏃",
      price: 58000,
      image: null,
      abilityUnit: null,
    },
  ],
  거실통로유도등: [
    {
      id: "room-passage-light-1",
      name: "표준형 거실통로유도등",
      description: "거실 및 개방 공간 통로에 설치하는 기본형 유도등",
      icon: "🛋️",
      price: 42000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "room-passage-light-2",
      name: "천장형 거실통로유도등",
      description: "천장에 부착해 넓은 공간을 비추는 유도등",
      icon: "🛋️",
      price: 48000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "room-passage-light-3",
      name: "슬림형 거실통로유도등",
      description: "인테리어에 어울리는 슬림한 디자인의 유도등",
      icon: "🛋️",
      price: 50000,
      image: null,
      abilityUnit: null,
    },
  ],
  계단통로유도등: [
    {
      id: "stair-light-1",
      name: "표준형 계단통로유도등",
      description: "계단실 벽면에 설치하는 기본형 통로유도등",
      icon: "🪜",
      price: 41000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "stair-light-2",
      name: "단수표시형 계단통로유도등",
      description: "층수와 단수를 함께 표시해주는 계단통로유도등",
      icon: "🪜",
      price: 53000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "stair-light-3",
      name: "축광형 계단통로유도등",
      description: "정전 시 잔광으로 계단 식별이 가능한 축광형 유도등",
      icon: "🪜",
      price: 46000,
      image: null,
      abilityUnit: null,
    },
  ],
  댐퍼: [
    {
      id: "damper-1",
      name: "방화댐퍼",
      description: "화재 확산을 막기 위해 덕트를 자동 차단하는 방화댐퍼",
      icon: "🌀",
      price: 180000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "damper-2",
      name: "방연댐퍼",
      description: "연기 확산을 막기 위해 설치하는 방연댐퍼",
      icon: "🌀",
      price: 195000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "damper-3",
      name: "모터구동형 댐퍼",
      description: "제어반 신호로 자동 개폐되는 모터구동형 댐퍼",
      icon: "🌀",
      price: 250000,
      image: null,
      abilityUnit: null,
    },
  ],
  발신기: [
    {
      id: "transmitter-1",
      name: "표준형 발신기",
      description: "수동으로 화재 신호를 발신하는 기본형 발신기",
      icon: "🔔",
      price: 22000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "transmitter-2",
      name: "발신기(응답램프 내장형)",
      description: "신호 수신 여부를 램프로 확인 가능한 발신기",
      icon: "🔔",
      price: 28000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "transmitter-3",
      name: "매입형 발신기",
      description: "벽면에 매립 설치하는 발신기",
      icon: "🔔",
      price: 25000,
      image: null,
      abilityUnit: null,
    },
  ],
  옥내소화전: [
    {
      id: "indoor-hydrant-1",
      name: "1호 옥내소화전함",
      description: "일반 건물에 적용하는 표준 1호 소화전함",
      icon: "🚒",
      price: 350000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "indoor-hydrant-2",
      name: "2호 옥내소화전함",
      description: "협소한 공간에 적합한 2호 소화전함",
      icon: "🚒",
      price: 280000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "indoor-hydrant-3",
      name: "호스릴 옥내소화전함",
      description: "한 사람이 조작하기 쉬운 호스릴 방식 소화전함",
      icon: "🚒",
      price: 420000,
      image: null,
      abilityUnit: null,
    },
  ],
  탬퍼스위치: [
    {
      id: "tamper-switch-1",
      name: "표준형 탬퍼스위치(T/S)",
      description: "개폐표시형밸브의 개폐 상태를 감시하는 표준형 탬퍼스위치",
      icon: "🔒",
      price: 32000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "tamper-switch-2",
      name: "매립형 탬퍼스위치(T/S)",
      description: "밸브 본체에 매립 설치하여 오작동을 줄인 탬퍼스위치",
      icon: "🔒",
      price: 41000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "tamper-switch-3",
      name: "방수형 탬퍼스위치(T/S)",
      description: "옥외 및 습기 많은 장소에 적합한 방수형 탬퍼스위치",
      icon: "🔒",
      price: 45000,
      image: null,
      abilityUnit: null,
    },
  ],
  압력스위치: [
    {
      id: "pressure-switch-1",
      name: "표준형 압력스위치(P/S)",
      description: "배관 내 압력 저하를 감지해 신호를 발신하는 표준형 압력스위치",
      icon: "🎚️",
      price: 35000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "pressure-switch-2",
      name: "디지털 압력스위치(P/S)",
      description: "압력 값을 디지털로 표시하고 설정값 조정이 쉬운 압력스위치",
      icon: "🎚️",
      price: 58000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "pressure-switch-3",
      name: "이중접점 압력스위치(P/S)",
      description: "기동용과 경보용 접점을 함께 갖춘 이중접점 압력스위치",
      icon: "🎚️",
      price: 62000,
      image: null,
      abilityUnit: null,
    },
  ],
  유수검지스위치: [
    {
      id: "flow-switch-1",
      name: "표준형 유수검지스위치(F/S)",
      description: "배관 내 유수 흐름을 감지해 화재 신호를 발신하는 플로우스위치",
      icon: "💦",
      price: 38000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "flow-switch-2",
      name: "패들형 유수검지스위치(F/S)",
      description: "패들(paddle) 방식으로 미세한 유수도 감지하는 플로우스위치",
      icon: "💦",
      price: 47000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "flow-switch-3",
      name: "지연회로 내장형 유수검지스위치(F/S)",
      description: "순간적인 압력변동에 의한 오작동을 방지하는 지연회로 내장형",
      icon: "💦",
      price: 53000,
      image: null,
      abilityUnit: null,
    },
  ],
  예비펌프: [
    {
      id: "standby-pump-1",
      name: "예비펌프 5마력",
      description: "주펌프 고장 시 자동 기동하는 소용량 예비펌프",
      icon: "🔄",
      price: 1650000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "standby-pump-2",
      name: "예비펌프 10마력",
      description: "중형 건물에 적용하는 예비펌프",
      icon: "🔄",
      price: 2450000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "standby-pump-3",
      name: "예비펌프 15마력",
      description: "대형 건물 및 고층 건물에 적용하는 예비펌프",
      icon: "🔄",
      price: 3200000,
      image: null,
      abilityUnit: null,
    },
  ],
  주펌프: [
    {
      id: "main-pump-1",
      name: "주펌프 10마력",
      description: "소규모 건물에 적용하는 전동기 직결형 주펌프",
      icon: "⚙️",
      price: 2800000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "main-pump-2",
      name: "주펌프 20마력",
      description: "중형 건물에 적용하는 표준형 주펌프",
      icon: "⚙️",
      price: 4100000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "main-pump-3",
      name: "주펌프 30마력",
      description: "대형 건물 및 고층 건물에 적용하는 고용량 주펌프",
      icon: "⚙️",
      price: 5600000,
      image: null,
      abilityUnit: null,
    },
  ],
  충압펌프: [
    {
      id: "jockey-pump-1",
      name: "충압펌프 1마력",
      description: "소규모 배관 계통의 압력을 유지하는 소용량 충압펌프",
      icon: "🚰",
      price: 580000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "jockey-pump-2",
      name: "충압펌프 2마력",
      description: "배관 내 압력 저하를 자동으로 보충하는 표준형 충압펌프",
      icon: "🚰",
      price: 720000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "jockey-pump-3",
      name: "충압펌프 3마력",
      description: "대형 배관 계통에 적용하는 고용량 충압펌프",
      icon: "🚰",
      price: 890000,
      image: null,
      abilityUnit: null,
    },
  ],
  급기팬: [
    {
      id: "supply-fan-1",
      name: "표준형 급기팬",
      description: "제연구역에 신선한 공기를 공급하는 표준형 급기송풍기",
      icon: "🌬️",
      price: 950000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "supply-fan-2",
      name: "고압형 급기팬",
      description: "계단실 및 부속실 가압을 위한 고압 급기송풍기",
      icon: "🌬️",
      price: 1350000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "supply-fan-3",
      name: "인버터 제어 급기팬",
      description: "풍량을 자동 제어하여 효율을 높인 인버터형 급기송풍기",
      icon: "🌬️",
      price: 1780000,
      image: null,
      abilityUnit: null,
    },
  ],
  배기팬: [
    {
      id: "exhaust-fan-1",
      name: "표준형 배기팬",
      description: "화재 시 연기를 옥외로 배출하는 표준형 배연송풍기",
      icon: "🌫️",
      price: 980000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exhaust-fan-2",
      name: "내열형 배기팬",
      description: "고온의 연기에도 견디는 내열 사양의 배연송풍기",
      icon: "🌫️",
      price: 1420000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exhaust-fan-3",
      name: "옥상형 배기팬",
      description: "옥상에 설치해 연기를 직상방으로 배출하는 배연송풍기",
      icon: "🌫️",
      price: 1250000,
      image: null,
      abilityUnit: null,
    },
  ],
  자동폐쇄장치: [
    {
      id: "auto-closer-1",
      name: "표준형 자동폐쇄장치",
      description: "화재 신호에 따라 방화문을 자동으로 닫아주는 표준형 도어릴리즈",
      icon: "🔐",
      price: 85000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "auto-closer-2",
      name: "전자석식 자동폐쇄장치",
      description: "전자석으로 문을 개방 유지하다 화재 시 해제하는 방식",
      icon: "🔐",
      price: 110000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "auto-closer-3",
      name: "댐퍼 연동형 자동폐쇄장치",
      description: "방화댐퍼와 연동하여 덕트를 자동으로 차단하는 폐쇄장치",
      icon: "🔐",
      price: 135000,
      image: null,
      abilityUnit: null,
    },
  ],
};
