import type { EquipmentName, EquipmentProduct } from "@/types/equipmentSelection";

export { NONE_PRODUCT_ID } from "@/types/equipmentSelection";

/**
 * 아래 설비는 able119(https://able119.co.kr/) 판매 페이지에 게시된 실제 제품명·가격·이미지를
 * 반영했습니다. (price/description은 able119 표기를 바탕으로 정리했고, image는 해당 상품 이미지를
 * 내려받아 frontend/public/images/equipment/ 에 저장한 것입니다.)
 * 소화기, 스프링클러, 차동식/정온식열감지기, 연기감지기,
 * 비상구/복도통로/거실통로/계단통로유도등, 발신기, 옥내소화전, 탬퍼스위치, 압력스위치,
 * 유수검지스위치, 댐퍼, 자동폐쇄장치
 *
 * 급기팬, 배기팬은 able119에 해당 상품이 없어 다나와(https://search.danawa.com/) 검색 결과의
 * 실제 산업용 송풍기/환풍기 상품명·가격을 대신 반영했습니다(오픈마켓 판매처 취합 특성상 제조사가
 * 명시되지 않은 상품이 많습니다). image는 출처 표기가 불명확한 오픈마켓 이미지라 내려받지 않고
 * null로 두었습니다.
 *
 * 예비펌프, 주펌프, 충압펌프는 able119는 물론 다나와에도 실제 상품이 없습니다(검색하면 세탁기,
 * 청소기 부품, 소방 표지판 스티커 등 무관한 상품만 매칭됨) — 프로젝트별 견적 제작되는 산업용
 * 소방펌프라 일반 가격비교 사이트에 카탈로그 상품으로 올라오지 않는 것으로 보입니다. 따라서 이
 * 3종은 아직 실제 제품 카탈로그/DB가 연동되기 전까지 사용하는 임시(목업) 데이터이며, 실제 제품
 * 정보와 무관합니다.
 *
 * 임시 데이터를 실제 제품으로 교체하려면 아래 EQUIPMENT_PRODUCTS의 각 항목에서:
 * - name, description: 실제 제품명/설명으로 바로 수정
 * - price: 원 단위 숫자로 입력 (예: 45000). 미정이면 null 유지
 * - image: 사진 파일을 frontend/public/images/equipment/ 에 넣고
 *          "/images/equipment/파일명.jpg" 형태의 경로를 입력 (없으면 null)
 * - abilityUnit: 다른 기능이 참조할 제품별 고유 정수 값 (예: 소화기 능력단위).
 *                설비마다 의미가 다를 수 있음. 미정이면 null 유지
 *
 * 소화기의 abilityUnit(능력단위)은 소화기 자동 배치(useExtinguisherPlacement)가 실제로
 * 계산에 사용합니다 — 모델별 정확한 형식승인 수치가 아니라, 무게(약제 중량) 구간별 KFI 능력단위
 * 인증 관행을 따른 근사값입니다(예: 3.3kg분말=3단위, 20kg 대형분말=10단위, CO2/청정소화기는
 * 무게 대비 다소 낮게 산정). 실제 형식승인서가 확보되면 해당 모델 값으로 교체해주세요.
 *
 * 차동식/정온식열감지기의 abilityUnit(보호면적, ㎡)도 열 감지기 자동 배치
 * (useHeatDetectorPlacement)가 실제로 계산에 사용합니다 — NFTC 203 감지기 바닥면적 표 중
 * "부착높이 4m 미만·기타구조·2종" 값을 모든 모델에 균일 적용한 근사값입니다(차동식=40㎡,
 * 정온식=15㎡). 카탈로그에 종별(1종/2종/특종)이나 내화구조 여부가 표기돼 있지 않아 모델별로
 * 세분화하지 않았습니다. 실제 형식승인서/설치 조건이 확보되면 해당 모델·조건 값으로 교체해주세요.
 *
 * 연기감지기의 abilityUnit(보호면적, ㎡)도 연기감지기 자동 배치(useSmokeDetectorPlacement,
 * 공동주택 세대 내 침실·거실 항목)가 실제로 계산에 사용합니다 — NFTC 203 표 2.4.3.5(연기감지기
 * 바닥면적) 중 "부착높이 4m 미만·2종" 값(150㎡)을 모든 모델에 균일 적용한 근사값입니다. 카탈로그에
 * 종별(1종/2종/3종)이나 부착높이가 표기돼 있지 않아 모델별로 세분화하지 않았습니다. 실제
 * 형식승인서/설치 조건이 확보되면 해당 모델·조건 값으로 교체해주세요.
 */
export const IS_MOCK_EQUIPMENT_DATA = true;

export const EQUIPMENT_LIST: EquipmentName[] = [
  "소화기",
  "스프링클러",
  "차동식열감지기",
  "정온식열감지기",
  "연기감지기",
  "비상구유도등",
  "복도통로유도등",
  "거실통로유도등",
  "계단통로유도등",
  "댐퍼",
  "발신기",
  "옥내소화전",
  "탬퍼스위치",
  "압력스위치",
  "유수검지스위치",
  "예비펌프",
  "주펌프",
  "충압펌프",
  "급기팬",
  "배기팬",
  "자동폐쇄장치",
];

/** 설비 선택 페이지에서 사용자가 고르기 전부터 카탈로그의 첫 제품을 기본 선택해두는 설비 (소화기/감지기류/유도등류/스프링클러/옥내소화전). 나머지는 미선택("선택 필요") 상태로 시작. */
export const DEFAULT_TO_FIRST_PRODUCT_EQUIPMENT: EquipmentName[] = [
  "소화기",
  "스프링클러",
  "차동식열감지기",
  "정온식열감지기",
  "연기감지기",
  "비상구유도등",
  "복도통로유도등",
  "거실통로유도등",
  "계단통로유도등",
  "옥내소화전",
];

export const EQUIPMENT_ICONS: Record<EquipmentName, string> = {
  소화기: "🧯",
  스프링클러: "💧",
  차동식열감지기: "🌡️",
  정온식열감지기: "🔥",
  연기감지기: "💨",
  비상구유도등: "🚪",
  복도통로유도등: "🏃",
  거실통로유도등: "🛋️",
  계단통로유도등: "🪜",
  댐퍼: "🌀",
  발신기: "🔔",
  옥내소화전: "🚒",
  탬퍼스위치: "🔒",
  압력스위치: "🎚️",
  유수검지스위치: "💦",
  예비펌프: "🔄",
  주펌프: "⚙️",
  충압펌프: "🚰",
  급기팬: "🌬️",
  배기팬: "🌫️",
  자동폐쇄장치: "🔐",
};

export const EQUIPMENT_PRODUCTS: Record<EquipmentName, EquipmentProduct[]> = {
  소화기: [
    {
      id: "extinguisher-1",
      name: "3.3kg ABC 분말소화기 (국산 축압식)",
      description: "3.3kg ABC 분말소화기, 국산 축압식",
      icon: "🧯",
      price: 20000,
      image: "/images/equipment/extinguisher-1.jpg",
      abilityUnit: 3,
    },
    {
      id: "extinguisher-2",
      name: "3.3kg ABC 분말소화기 (KFI검정품)",
      description: "3.3kg ABC 분말소화기, KFI 국가검정품",
      icon: "🧯",
      price: 16500,
      image: "/images/equipment/extinguisher-2.jpg",
      abilityUnit: 3,
    },
    {
      id: "extinguisher-3",
      name: "2.5kg 분말소화기",
      description: "2.5kg 분말소화기, 가정·사무실용",
      icon: "🧯",
      price: 22000,
      image: "/images/equipment/extinguisher-3.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-4",
      name: "1.5kg 분말소화기",
      description: "1.5kg 분말소화기, 고시원·업소용",
      icon: "🧯",
      price: 18700,
      image: "/images/equipment/extinguisher-4.jpg",
      abilityUnit: 1,
    },
    {
      id: "extinguisher-5",
      name: "4.5kg 분말소화기",
      description: "4.5kg 분말소화기, 공장·창고용",
      icon: "🧯",
      price: 35200,
      image: "/images/equipment/extinguisher-5.jpg",
      abilityUnit: 4,
    },
    {
      id: "extinguisher-6",
      name: "6.5kg 분말소화기",
      description: "6.5kg 분말소화기, 유류 저장소용",
      icon: "🧯",
      price: 49500,
      image: "/images/equipment/extinguisher-6.jpg",
      abilityUnit: 5,
    },
    {
      id: "extinguisher-7",
      name: "20kg 분말소화기",
      description: "20kg 분말소화기, 대형화재용 축압식",
      icon: "🧯",
      price: 145000,
      image: "/images/equipment/extinguisher-7.jpg",
      abilityUnit: 10,
    },
    {
      id: "extinguisher-8",
      name: "0.7kg 분말소화기 (차량용)",
      description: "0.7kg 분말소화기, 차량용 거치대 포함",
      icon: "🧯",
      price: 18700,
      image: "/images/equipment/extinguisher-8.jpg",
      abilityUnit: 1,
    },
    {
      id: "extinguisher-9",
      name: "3.3kg 분말소화기 (자동차 겸용)",
      description: "3.3kg 분말소화기, 자동차 겸용 KFI검정품",
      icon: "🧯",
      price: 28000,
      image: "/images/equipment/extinguisher-9.jpg",
      abilityUnit: 3,
    },
    {
      id: "extinguisher-10",
      name: "2.3kg CO2소화기",
      description: "2.3kg CO2소화기, 통신·전기실용",
      icon: "🧯",
      price: 83600,
      image: "/images/equipment/extinguisher-10.jpg",
      abilityUnit: 1,
    },
    {
      id: "extinguisher-11",
      name: "4.6kg CO2소화기",
      description: "4.6kg CO2소화기, 전기실·주유소용",
      icon: "🧯",
      price: 143000,
      image: "/images/equipment/extinguisher-11.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-12",
      name: "6.8kg CO2소화기",
      description: "6.8kg CO2소화기, 주유소·항공기용",
      icon: "🧯",
      price: 181500,
      image: "/images/equipment/extinguisher-12.jpg",
      abilityUnit: 3,
    },
    {
      id: "extinguisher-13",
      name: "CEA-123 청정소화기 2.5kg",
      description: "청정소화기 2.5kg, HCFC-123 약제",
      icon: "🧯",
      price: 137000,
      image: "/images/equipment/extinguisher-13.jpg",
      abilityUnit: 1,
    },
    {
      id: "extinguisher-14",
      name: "CEA-123 청정소화기 3kg",
      description: "청정소화기 3kg, HCFC-123 약제",
      icon: "🧯",
      price: 155000,
      image: "/images/equipment/extinguisher-14.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-15",
      name: "FORT-236 청정소화기 3.0kg",
      description: "FORT-236 청정소화기 3.0kg, HFC-236FA",
      icon: "🧯",
      price: 178000,
      image: "/images/equipment/extinguisher-15.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-16",
      name: "DA-123 청정소화기 3kg",
      description: "DA-123 청정소화기 3kg, 스텐 용기",
      icon: "🧯",
      price: 165000,
      image: "/images/equipment/extinguisher-16.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-17",
      name: "HTC236 청정소화기 3.0kg",
      description: "HTC236 청정소화기 3.0kg, HFC-236FA",
      icon: "🧯",
      price: 170500,
      image: "/images/equipment/extinguisher-17.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-18",
      name: "HTC123 청정소화기 3.0kg",
      description: "HTC123 청정소화기 3.0kg, HCFC-123",
      icon: "🧯",
      price: 168300,
      image: "/images/equipment/extinguisher-18.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-19",
      name: "FORT-5112 청정소화기 3kg",
      description: "FORT-5112 청정소화기 3kg, FK-5-1-12",
      icon: "🧯",
      price: 129900,
      image: "/images/equipment/extinguisher-19.jpg",
      abilityUnit: 2,
    },
    {
      id: "extinguisher-20",
      name: "노벡소화기 ECO-5112 4.0kg",
      description: "노벡소화기 ECO-5112 4.0kg, 비전도성",
      icon: "🧯",
      price: 129800,
      image: "/images/equipment/extinguisher-20.jpg",
      abilityUnit: 2,
    },
  ],
  스프링클러: [
    {
      id: "sprinkler-1",
      name: "SP일반헤드 상향식 72℃",
      description: "SP일반헤드 상향식 72℃, 폐쇄형 휴즈블링크",
      icon: "💧",
      price: 5000,
      image: "/images/equipment/sprinkler-1.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-2",
      name: "SP일반헤드 하향식 72℃",
      description: "SP일반헤드 하향식 72℃, 폐쇄형 휴즈블링크",
      icon: "💧",
      price: 5000,
      image: "/images/equipment/sprinkler-2.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-3",
      name: "SP일반헤드 상향식 105℃",
      description: "SP일반헤드 상향식 105℃, 폐쇄형 휴즈블링크",
      icon: "💧",
      price: 5500,
      image: "/images/equipment/sprinkler-3.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-4",
      name: "SP일반헤드 하향식 105℃",
      description: "SP일반헤드 하향식 105℃, 폐쇄형 휴즈블링크",
      icon: "💧",
      price: 5500,
      image: "/images/equipment/sprinkler-4.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-5",
      name: "SP일반헤드 상향식 143℃",
      description: "SP일반헤드 상향식 143℃, 폐쇄형",
      icon: "💧",
      price: 13750,
      image: "/images/equipment/sprinkler-5.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-6",
      name: "SP일반헤드 하향식 143℃",
      description: "SP일반헤드 하향식 143℃, 폐쇄형",
      icon: "💧",
      price: 13750,
      image: "/images/equipment/sprinkler-6.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-7",
      name: "원형헤드 72℃",
      description: "원형헤드 72℃, 헤드왕 포함",
      icon: "💧",
      price: 22000,
      image: "/images/equipment/sprinkler-7.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-8",
      name: "원형헤드 105℃",
      description: "원형헤드 105℃, 헤드왕 포함",
      icon: "💧",
      price: 22000,
      image: "/images/equipment/sprinkler-8.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-9",
      name: "측벽헤드 72℃",
      description: "측벽헤드 72℃, 폐쇄형 측벽형",
      icon: "💧",
      price: 6050,
      image: "/images/equipment/sprinkler-9.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-10",
      name: "측벽헤드 105℃",
      description: "측벽헤드 105℃, 폐쇄형 측벽형",
      icon: "💧",
      price: 6600,
      image: "/images/equipment/sprinkler-10.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-11",
      name: "플래쉬헤드 표준일반 72℃",
      description: "플래쉬헤드 표준일반 72℃",
      icon: "💧",
      price: 6050,
      image: "/images/equipment/sprinkler-11.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-12",
      name: "플래쉬헤드 표준일반 105℃",
      description: "플래쉬헤드 표준일반 105℃",
      icon: "💧",
      price: 6380,
      image: "/images/equipment/sprinkler-12.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-13",
      name: "플래쉬헤드 조기반응형 72℃",
      description: "플래쉬헤드 조기반응형 72℃",
      icon: "💧",
      price: 6050,
      image: "/images/equipment/sprinkler-13.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-14",
      name: "플래쉬헤드 조기반응형 105℃",
      description: "플래쉬헤드 조기반응형 105℃",
      icon: "💧",
      price: 6270,
      image: "/images/equipment/sprinkler-14.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-15",
      name: "살수헤드",
      description: "살수헤드 15A/20A, 개방형",
      icon: "💧",
      price: 5500,
      image: "/images/equipment/sprinkler-15.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-16",
      name: "개방형헤드",
      description: "개방형헤드, 상향식/하향식 표준형",
      icon: "💧",
      price: 4400,
      image: "/images/equipment/sprinkler-16.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-17",
      name: "간이스프링클러헤드 K50",
      description: "간이스프링클러헤드 K50, 유리벌브형",
      icon: "💧",
      price: 8800,
      image: "/images/equipment/sprinkler-17.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-18",
      name: "글라스헤드 일반형 68℃",
      description: "글라스헤드 일반형 68℃, 유리벌브형",
      icon: "💧",
      price: 3200,
      image: "/images/equipment/sprinkler-18.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-19",
      name: "글라스헤드 일반형 93℃",
      description: "글라스헤드 일반형 93℃, 유리벌브형",
      icon: "💧",
      price: 3400,
      image: "/images/equipment/sprinkler-19.jpg",
      abilityUnit: null,
    },
    {
      id: "sprinkler-20",
      name: "컨실드헤드",
      description: "컨실드헤드 72/105℃, 매립형",
      icon: "💧",
      price: 35000,
      image: "/images/equipment/sprinkler-20.jpg",
      abilityUnit: null,
    },
  ],
  차동식열감지기: [
    {
      id: "heat-differential-1",
      name: "차동식 스포트형 감지기 (보급형)",
      description: "차동식 스포트형 감지기, DC24V 보급형",
      icon: "🌡️",
      price: 4180,
      image: "/images/equipment/heat-differential-1.jpg",
      abilityUnit: 40,
    },
    {
      id: "heat-differential-2",
      name: "차동식 스포트형 감지기 [화경산업]",
      description: "차동식 스포트형 감지기, DC24V [화경산업]",
      icon: "🌡️",
      price: 4950,
      image: "/images/equipment/heat-differential-2.jpg",
      abilityUnit: 40,
    },
    {
      id: "heat-differential-3",
      name: "차동식 스포트형 감지기 [동방] P101-15000",
      description: "차동식 스포트형 감지기(동방), DC24V P101-15000",
      icon: "🌡️",
      price: 4950,
      image: "/images/equipment/heat-differential-3.jpg",
      abilityUnit: 40,
    },
    {
      id: "heat-differential-4",
      name: "차동식 2종 감지기 [지멘스] SRA-2A",
      description: "차동식 2종 스포트형 감지기(지멘스), SRA-2A",
      icon: "🌡️",
      price: 6050,
      image: "/images/equipment/heat-differential-4.jpg",
      abilityUnit: 40,
    },
    {
      id: "heat-differential-5",
      name: "차동식 기계식 감지기 [지멘스] DSG-2-O",
      description: "차동식 기계식 감지기(지멘스), DSG-2-O",
      icon: "🌡️",
      price: 9000,
      image: "/images/equipment/heat-differential-5.jpg",
      abilityUnit: 40,
    },
    {
      id: "heat-differential-6",
      name: "차동식 스포트형 감지기 [올라이트]",
      description: "차동식 스포트형 감지기, DC24V [올라이트]",
      icon: "🌡️",
      price: 4840,
      image: "/images/equipment/heat-differential-6.jpg",
      abilityUnit: 40,
    },
    {
      id: "heat-differential-7",
      name: "GFS 차동식 감지기 RHD-2003GS",
      description: "GFS 차동식 스포트형 감지기, RHD-2003GS",
      icon: "🌡️",
      price: 4950,
      image: "/images/equipment/heat-differential-7.jpg",
      abilityUnit: 40,
    },
    {
      id: "heat-differential-8",
      name: "차동식 반도체식 감지기 [케이텔]",
      description: "차동식 반도체식 감지기(케이텔), DC24V",
      icon: "🌡️",
      price: 4400,
      image: "/images/equipment/heat-differential-8.jpg",
      abilityUnit: 40,
    },
  ],
  정온식열감지기: [
    {
      id: "heat-fixed-1",
      name: "정온식 스포트형 감지기 70℃ (보급형)",
      description: "정온식 스포트형 감지기, DC24V 70도 보급형",
      icon: "🔥",
      price: 4180,
      image: "/images/equipment/heat-fixed-1.jpg",
      abilityUnit: 15,
    },
    {
      id: "heat-fixed-2",
      name: "정온식 스포트형 감지기 70℃ [화경산업]",
      description: "정온식 스포트형 감지기, DC24V 70도 [화경산업]",
      icon: "🔥",
      price: 4840,
      image: "/images/equipment/heat-fixed-2.jpg",
      abilityUnit: 15,
    },
    {
      id: "heat-fixed-3",
      name: "정온식 스포트형 감지기 [동방] 70℃",
      description: "정온식 스포트형 감지기(동방), 24V 70도",
      icon: "🔥",
      price: 4900,
      image: "/images/equipment/heat-fixed-3.jpg",
      abilityUnit: 15,
    },
    {
      id: "heat-fixed-4",
      name: "정온식 스포트형 감지기 [동방] 110℃",
      description: "정온식 스포트형 감지기(동방), 24V 110도",
      icon: "🔥",
      price: 8250,
      image: "/images/equipment/heat-fixed-4.jpg",
      abilityUnit: 15,
    },
    {
      id: "heat-fixed-5",
      name: "정온식 스포트형 감지기 [지멘스] FTE-70A",
      description: "정온식 스포트형 감지기(지멘스), 70도 FTE-70A",
      icon: "🔥",
      price: 6050,
      image: "/images/equipment/heat-fixed-5.jpg",
      abilityUnit: 15,
    },
    {
      id: "heat-fixed-6",
      name: "정온식 스포트형 감지기 70℃ [올라이트]",
      description: "정온식 스포트형 감지기, DC24V 70도 [올라이트]",
      icon: "🔥",
      price: 4840,
      image: "/images/equipment/heat-fixed-6.jpg",
      abilityUnit: 15,
    },
    {
      id: "heat-fixed-7",
      name: "GFS 정온식 감지기 FHD-4001GS",
      description: "GFS 정온식 스포트형 감지기, FHD-4001GS",
      icon: "🔥",
      price: 4950,
      image: "/images/equipment/heat-fixed-7.jpg",
      abilityUnit: 15,
    },
    {
      id: "heat-fixed-8",
      name: "정온식 반도체식 감지기 [케이텔]",
      description: "정온식 반도체식 감지기(케이텔), DC24V",
      icon: "🔥",
      price: 4500,
      image: "/images/equipment/heat-fixed-8.jpg",
      abilityUnit: 15,
    },
  ],
  연기감지기: [
    {
      id: "smoke-1",
      name: "광전식 연기감지기 (비축적형 보급형)",
      description: "광전식 연기감지기, DC24V 비축적형 보급형",
      icon: "💨",
      price: 6600,
      image: "/images/equipment/smoke-1.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-2",
      name: "광전식 연기감지기 [화경산업]",
      description: "광전식 연기감지기, DC24V 비축적형 [화경산업]",
      icon: "💨",
      price: 7150,
      image: "/images/equipment/smoke-2.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-3",
      name: "광전식 연기감지기 [동방] 비축적형",
      description: "광전식 연기감지기(동방), 비축적형 24V",
      icon: "💨",
      price: 12650,
      image: "/images/equipment/smoke-3.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-4",
      name: "광전식 연기감지기 [지멘스] PSA-2B",
      description: "광전식 연기감지기(지멘스), 비축적형 24V PSA-2B",
      icon: "💨",
      price: 14300,
      image: "/images/equipment/smoke-4.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-5",
      name: "광전식 연기감지기 [동방] 축적형",
      description: "광전식 연기감지기(동방), 축적형 24V",
      icon: "💨",
      price: 16500,
      image: "/images/equipment/smoke-5.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-6",
      name: "GFS 광전식 연기감지기 PSD-3001GS",
      description: "GFS 광전식 스포트형 연기감지기, PSD-3001GS",
      icon: "💨",
      price: 12650,
      image: "/images/equipment/smoke-6.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-7",
      name: "광전식 연기감지기 [올라이트]",
      description: "광전식 연기감지기, DC24V [올라이트]",
      icon: "💨",
      price: 13200,
      image: "/images/equipment/smoke-7.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-8",
      name: "저전류형 연기감지기 [화경산업]",
      description: "저전류형 연기감지기, DC24V [화경산업]",
      icon: "💨",
      price: 6930,
      image: "/images/equipment/smoke-8.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-9",
      name: "광전식 연기감지기 [케이텔] 감23-12",
      description: "광전식 연기감지기(케이텔), DC24V 감23-12",
      icon: "💨",
      price: 7500,
      image: "/images/equipment/smoke-9.jpg",
      abilityUnit: 150,
    },
    {
      id: "smoke-10",
      name: "단독경보형 연기감지기 LTD-3700A",
      description: "단독경보형 연기감지기, 음성멘트+시각경보",
      icon: "💨",
      price: 41900,
      image: "/images/equipment/smoke-10.jpg",
      abilityUnit: 150,
    },
  ],
  비상구유도등: [
    {
      id: "exit-light-1",
      name: "피난구유도등 소형 기본형",
      description: "피난구유도등 소형 기본형, 벽부형 200x150mm",
      icon: "🚪",
      price: 10450,
      image: "/images/equipment/exit-light-1.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-2",
      name: "피난구유도등 소형 좌방향",
      description: "피난구유도등 소형 좌방향, 벽부형 200x150mm",
      icon: "🚪",
      price: 12000,
      image: "/images/equipment/exit-light-2.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-3",
      name: "피난구유도등 소형 양방향",
      description: "피난구유도등 소형 양방향, 벽부형 200x150mm",
      icon: "🚪",
      price: 12000,
      image: "/images/equipment/exit-light-3.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-4",
      name: "피난구유도등 소형 우방향",
      description: "피난구유도등 소형 우방향, 벽부형 200x150mm",
      icon: "🚪",
      price: 12000,
      image: "/images/equipment/exit-light-4.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-5",
      name: "피난구유도등 중형 기본형",
      description: "피난구유도등 중형 기본형, 벽부형 270x230mm",
      icon: "🚪",
      price: 17600,
      image: "/images/equipment/exit-light-5.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-6",
      name: "피난구유도등 중형 좌방향",
      description: "피난구유도등 중형 좌방향, 벽부형 270x230mm",
      icon: "🚪",
      price: 19250,
      image: "/images/equipment/exit-light-6.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-7",
      name: "피난구유도등 중형 양방향",
      description: "피난구유도등 중형 양방향, 벽부형 270x230mm",
      icon: "🚪",
      price: 19250,
      image: "/images/equipment/exit-light-7.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-8",
      name: "피난구유도등 중형 우방향",
      description: "피난구유도등 중형 우방향, 벽부형 270x230mm",
      icon: "🚪",
      price: 19250,
      image: "/images/equipment/exit-light-8.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-9",
      name: "피난구유도등K 와이드형 중형",
      description: "피난구유도등K 와이드형 중형(K-Tel)",
      icon: "🚪",
      price: 56000,
      image: "/images/equipment/exit-light-9.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-10",
      name: "와이드피난구유도등 L-10",
      description: "와이드피난구유도등 wide형 중형 L-10",
      icon: "🚪",
      price: 53500,
      image: "/images/equipment/exit-light-10.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-11",
      name: "피난구유도등 대형 기본형",
      description: "피난구유도등 대형 기본형, 벽부형 325x290mm",
      icon: "🚪",
      price: 27500,
      image: "/images/equipment/exit-light-11.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-12",
      name: "피난구유도등 대형 좌방향",
      description: "피난구유도등 대형 좌방향, 벽부형 325x290mm",
      icon: "🚪",
      price: 30000,
      image: "/images/equipment/exit-light-12.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-13",
      name: "피난구유도등 대형 양방향",
      description: "피난구유도등 대형 양방향, 벽부형 325x290mm",
      icon: "🚪",
      price: 30000,
      image: "/images/equipment/exit-light-13.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-14",
      name: "피난구유도등 대형 우방향",
      description: "피난구유도등 대형 우방향, 벽부형 325x290mm",
      icon: "🚪",
      price: 30000,
      image: "/images/equipment/exit-light-14.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-15",
      name: "피난구유도등(NEO) 소형",
      description: "피난구유도등(NEO) 소형, 벽부형 LED",
      icon: "🚪",
      price: 22550,
      image: "/images/equipment/exit-light-15.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-16",
      name: "피난구유도등(NEO) 중형",
      description: "피난구유도등(NEO) 중형, 벽부형 LED",
      icon: "🚪",
      price: 28600,
      image: "/images/equipment/exit-light-16.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-17",
      name: "피난구유도등(NEO) 대형",
      description: "피난구유도등(NEO) 대형, 벽부형 LED",
      icon: "🚪",
      price: 41800,
      image: "/images/equipment/exit-light-17.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-18",
      name: "피난구유도등(NEO) 와이드형 중형",
      description: "피난구유도등(NEO) 와이드형 중형, 벽부형 LED",
      icon: "🚪",
      price: 57750,
      image: "/images/equipment/exit-light-18.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-19",
      name: "입체형피난구유도등 LTE-PS 소형",
      description: "입체형피난구유도등 LTE-PS 소형, 3면체",
      icon: "🚪",
      price: 93500,
      image: "/images/equipment/exit-light-19.jpg",
      abilityUnit: null,
    },
    {
      id: "exit-light-20",
      name: "입체형유도등 HK-710 소형 [화경산업]",
      description: "입체형유도등 HK-710 소형, 3면형 [화경산업]",
      icon: "🚪",
      price: 82500,
      image: "/images/equipment/exit-light-20.jpg",
      abilityUnit: null,
    },
  ],
  복도통로유도등: [
    {
      id: "corridor-light-1",
      name: "복도통로유도등 벽부형 좌방향 [현대방재]",
      description: "복도통로유도등 벽부형 좌방향, 200x150mm [현대방재]",
      icon: "🏃",
      price: 11000,
      image: "/images/equipment/corridor-light-1.jpg",
      abilityUnit: null,
    },
    {
      id: "corridor-light-2",
      name: "복도통로유도등 벽부형 양방향 [현대방재]",
      description: "복도통로유도등 벽부형 양방향, 200x150mm [현대방재]",
      icon: "🏃",
      price: 11000,
      image: "/images/equipment/corridor-light-2.jpg",
      abilityUnit: null,
    },
    {
      id: "corridor-light-3",
      name: "복도통로유도등 벽부형 우방향 [현대방재]",
      description: "복도통로유도등 벽부형 우방향, 200x150mm [현대방재]",
      icon: "🏃",
      price: 11000,
      image: "/images/equipment/corridor-light-3.jpg",
      abilityUnit: null,
    },
    {
      id: "corridor-light-4",
      name: "입체형 복도통로유도등 LTE-2PA 소형",
      description: "입체형 복도통로유도등 LTE-2PA 소형, 2면체",
      icon: "🏃",
      price: 82500,
      image: "/images/equipment/corridor-light-4.jpg",
      abilityUnit: null,
    },
    {
      id: "corridor-light-5",
      name: "복도통로유도등(NEO) 벽부형",
      description: "복도통로유도등(NEO) 벽부형 LED, 155x155mm",
      icon: "🏃",
      price: 22550,
      image: "/images/equipment/corridor-light-5.jpg",
      abilityUnit: null,
    },
    {
      id: "corridor-light-6",
      name: "입체형유도등 HK-327 복도통로유도등 [화경산업]",
      description: "입체형유도등 HK-327 복도통로유도등 소형 [화경산업]",
      icon: "🏃",
      price: 78000,
      image: "/images/equipment/corridor-light-6.jpg",
      abilityUnit: null,
    },
  ],
  거실통로유도등: [
    {
      id: "room-passage-light-1",
      name: "거실통로유도등 소형 좌방향",
      description: "거실통로유도등 소형 좌방향, 벽부형 180x165mm",
      icon: "🛋️",
      price: 18000,
      image: "/images/equipment/room-passage-light-1.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-2",
      name: "거실통로유도등 소형 양방향",
      description: "거실통로유도등 소형 양방향, 벽부형 180x165mm",
      icon: "🛋️",
      price: 18000,
      image: "/images/equipment/room-passage-light-2.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-3",
      name: "거실통로유도등 소형 우방향",
      description: "거실통로유도등 소형 우방향, 벽부형 180x165mm",
      icon: "🛋️",
      price: 18000,
      image: "/images/equipment/room-passage-light-3.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-4",
      name: "거실통로유도등 중형 좌방향",
      description: "거실통로유도등 중형 좌방향, 벽부형 270x251mm",
      icon: "🛋️",
      price: 25300,
      image: "/images/equipment/room-passage-light-4.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-5",
      name: "거실통로유도등 중형 양방향",
      description: "거실통로유도등 중형 양방향, 벽부형 270x251mm",
      icon: "🛋️",
      price: 25300,
      image: "/images/equipment/room-passage-light-5.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-6",
      name: "거실통로유도등 중형 우방향",
      description: "거실통로유도등 중형 우방향, 벽부형 270x251mm",
      icon: "🛋️",
      price: 25300,
      image: "/images/equipment/room-passage-light-6.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-7",
      name: "거실통로유도등(NEO) 중형 벽부형",
      description: "거실통로유도등(NEO) 중형, 벽부형 LED",
      icon: "🛋️",
      price: 31900,
      image: "/images/equipment/room-passage-light-7.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-8",
      name: "거실통로유도등(NEO) 천정형 중형",
      description: "거실통로유도등(NEO) 천정형 중형, LED",
      icon: "🛋️",
      price: 41800,
      image: "/images/equipment/room-passage-light-8.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-9",
      name: "거실통로유도등 중형 [금호유도등]",
      description: "거실통로유도등 중형 [금호유도등], 좌/우/양 선택",
      icon: "🛋️",
      price: 41800,
      image: "/images/equipment/room-passage-light-9.jpg",
      abilityUnit: null,
    },
    {
      id: "room-passage-light-10",
      name: "거실통로유도등LK 대형",
      description: "거실통로유도등LK 대형, 벽부형 477x482mm",
      icon: "🛋️",
      price: 297000,
      image: "/images/equipment/room-passage-light-10.webp",
      abilityUnit: null,
    },
  ],
  계단통로유도등: [
    {
      id: "stair-light-1",
      name: "계단통로유도등(신형-소형) 좌상우하",
      description: "계단통로유도등(신형-소형) 좌상우하, 층수기재 고급형",
      icon: "🪜",
      price: 18700,
      image: "/images/equipment/stair-light-1.jpg",
      abilityUnit: null,
    },
    {
      id: "stair-light-2",
      name: "계단통로유도등(신형-소형) 좌하우상",
      description: "계단통로유도등(신형-소형) 좌하우상, 층수기재 고급형",
      icon: "🪜",
      price: 18700,
      image: "/images/equipment/stair-light-2.jpg",
      abilityUnit: null,
    },
    {
      id: "stair-light-3",
      name: "계단통로유도등(NEO) 벽부형",
      description: "계단통로유도등(NEO) 벽부형, LED 좌상우하/좌하우상",
      icon: "🪜",
      price: 27500,
      image: "/images/equipment/stair-light-3.jpg",
      abilityUnit: null,
    },
    {
      id: "stair-light-4",
      name: "계단통로유도등(중형) [화경산업] 좌하우상",
      description: "계단통로유도등(중형) [화경산업], 좌하우상/층수유무 선택",
      icon: "🪜",
      price: 35200,
      image: "/images/equipment/stair-light-4.jpg",
      abilityUnit: null,
    },
    {
      id: "stair-light-5",
      name: "계단통로유도등(중형) [화경산업] 좌상우하",
      description: "계단통로유도등(중형) [화경산업], 좌상우하/층수유무 선택",
      icon: "🪜",
      price: 35200,
      image: "/images/equipment/stair-light-5.jpg",
      abilityUnit: null,
    },
  ],
  발신기: [
    {
      id: "transmitter-1",
      name: "화재발신기 (보급형)",
      description: "화재발신기(보급형), DC24V 100mA",
      icon: "🔔",
      price: 3850,
      image: "/images/equipment/transmitter-1.jpg",
      abilityUnit: null,
    },
    {
      id: "transmitter-2",
      name: "발신기 [동방] P301-06000",
      description: "발신기(동방) P301-06000, 4P 일반용",
      icon: "🔔",
      price: 8250,
      image: "/images/equipment/transmitter-2.jpg",
      abilityUnit: null,
    },
    {
      id: "transmitter-3",
      name: "수동발신기 [지멘스] P형/R형/M형",
      description: "수동발신기(지멘스), DC24V P형/R형/M형",
      icon: "🔔",
      price: 14200,
      image: "/images/equipment/transmitter-3.jpg",
      abilityUnit: null,
    },
    {
      id: "transmitter-4",
      name: "방수형발신기 HK-06",
      description: "방수형발신기 HK-06, IP6/7등급 KFI검정품",
      icon: "🔔",
      price: 69000,
      image: "/images/equipment/transmitter-4.jpg",
      abilityUnit: null,
    },
    {
      id: "transmitter-5",
      name: "수동 화재발신기 [화경산업]",
      description: "수동 화재발신기[화경산업], DC24V 100mA",
      icon: "🔔",
      price: 5390,
      image: "/images/equipment/transmitter-5.jpg",
      abilityUnit: null,
    },
    {
      id: "transmitter-6",
      name: "수동발신기 [지멘스] MCL-O",
      description: "수동발신기(지멘스) MCL-O, DC24V 100mA",
      icon: "🔔",
      price: 7700,
      image: "/images/equipment/transmitter-6.jpg",
      abilityUnit: null,
    },
    {
      id: "transmitter-7",
      name: "발신기 [GFS] ACBR-04",
      description: "발신기(GFS) ACBR-04, DC24V P형 옥내형",
      icon: "🔔",
      price: 7700,
      image: "/images/equipment/transmitter-7.jpg",
      abilityUnit: null,
    },
  ],
  옥내소화전: [
    {
      id: "indoor-hydrant-1",
      name: "옥내소화전함 노출형 (철재)",
      description: "옥내소화전함 노출형, 철재 640x180x1190mm",
      icon: "🚒",
      price: 143000,
      image: "/images/equipment/indoor-hydrant-1.webp",
      abilityUnit: null,
    },
    {
      id: "indoor-hydrant-2",
      name: "옥내소화전함 노출형 (스텐)",
      description: "옥내소화전함 노출형, 스텐 1.5t",
      icon: "🚒",
      price: 211000,
      image: "/images/equipment/indoor-hydrant-2.jpg",
      abilityUnit: null,
    },
    {
      id: "indoor-hydrant-3",
      name: "옥내소화전함 다리부착형 (스텐)",
      description: "옥내소화전함 다리부착형, 스텐 640x180x1340mm",
      icon: "🚒",
      price: 255000,
      image: "/images/equipment/indoor-hydrant-3.jpg",
      abilityUnit: null,
    },
    {
      id: "indoor-hydrant-4",
      name: "호스릴 옥내소화전함 DY (매립형)",
      description: "호스릴 옥내소화전함 DY, 매립형 호스릴내장",
      icon: "🚒",
      price: 502700,
      image: "/images/equipment/indoor-hydrant-4.jpg",
      abilityUnit: null,
    },
    {
      id: "indoor-hydrant-5",
      name: "호스릴 옥내소화전함 DL (노출형)",
      description: "호스릴 옥내소화전함 DL, 노출형 스텐",
      icon: "🚒",
      price: 638000,
      image: "/images/equipment/indoor-hydrant-5.jpg",
      abilityUnit: null,
    },
  ],
  탬퍼스위치: [
    {
      id: "tamper-switch-1",
      name: "탬퍼스위치B (OSY용 스위치식)",
      description: "탬퍼스위치B, OSY용 스위치식 40A-250A",
      icon: "🔒",
      price: 9900,
      image: "/images/equipment/tamper-switch-1.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-2",
      name: "탬퍼스위치A (OSY용 자석식)",
      description: "탬퍼스위치A, OSY용 자석식",
      icon: "🔒",
      price: 10450,
      image: "/images/equipment/tamper-switch-2.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-3",
      name: "탬퍼스위치 방수형 (40A-200A)",
      description: "탬퍼스위치 방수형, 40A-200A 구경 선택",
      icon: "🔒",
      price: 17490,
      image: "/images/equipment/tamper-switch-3.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-4",
      name: "탬퍼스위치D (버터플라이밸브용)",
      description: "탬퍼스위치D, 버터플라이밸브용 자석식/기어용",
      icon: "🔒",
      price: 12100,
      image: "/images/equipment/tamper-switch-4.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-5",
      name: "탬퍼스위치C (레버타입)",
      description: "탬퍼스위치C, 버터플라이밸브용 레버타입",
      icon: "🔒",
      price: 9900,
      image: "/images/equipment/tamper-switch-5.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-6",
      name: "탬퍼스위치R (볼밸브용)",
      description: "탬퍼스위치R, 볼밸브용",
      icon: "🔒",
      price: 9900,
      image: "/images/equipment/tamper-switch-6.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-7",
      name: "탬퍼스위치K (비주얼 캡형)",
      description: "탬퍼스위치K, 비주얼 캡형 버터V/V 기어형",
      icon: "🔒",
      price: 16500,
      image: "/images/equipment/tamper-switch-7.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-8",
      name: "템퍼스위치 (비주얼LED형)",
      description: "템퍼스위치(비주얼형), 비주얼LED템퍼스위치",
      icon: "🔒",
      price: 27500,
      image: "/images/equipment/tamper-switch-8.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-9",
      name: "템퍼스위치 방수형 (40-65A)",
      description: "템퍼스위치 방수형, 40-65A",
      icon: "🔒",
      price: 17490,
      image: "/images/equipment/tamper-switch-9.jpg",
      abilityUnit: null,
    },
    {
      id: "tamper-switch-10",
      name: "방폭형 탬퍼스위치 HK-TAS",
      description: "방폭형 탬퍼스위치 HK-TAS, 50A~300A",
      icon: "🔒",
      price: 209000,
      image: "/images/equipment/tamper-switch-10.jpg",
      abilityUnit: null,
    },
  ],
  압력스위치: [
    {
      id: "pressure-switch-1",
      name: "압력스위치 HS-210 (10kg용)",
      description: "압력스위치, 물압력 10kg HS-210",
      icon: "🎚️",
      price: 17600,
      image: "/images/equipment/pressure-switch-1.jpg",
      abilityUnit: null,
    },
    {
      id: "pressure-switch-2",
      name: "압력스위치 HS-220 (20kg용)",
      description: "압력스위치, 물압력 20kg HS-220",
      icon: "🎚️",
      price: 17600,
      image: "/images/equipment/pressure-switch-2.jpg",
      abilityUnit: null,
    },
    {
      id: "pressure-switch-3",
      name: "압력스위치 [SAGiNOMIYA] SNS-C120 (20kg용)",
      description: "압력스위치[SAGiNOMIYA] SNS-C120, 20kg용",
      icon: "🎚️",
      price: 50600,
      image: "/images/equipment/pressure-switch-3.jpg",
      abilityUnit: null,
    },
    {
      id: "pressure-switch-4",
      name: "압력스위치 [SAGiNOMIYA] SNS-C110 (10kg용)",
      description: "압력스위치[SAGiNOMIYA] SNS-C110, 10kg용",
      icon: "🎚️",
      price: 48400,
      image: "/images/equipment/pressure-switch-4.jpg",
      abilityUnit: null,
    },
    {
      id: "pressure-switch-5",
      name: "방폭형 압력스위치 HK-FPC",
      description: "방폭형 압력스위치 HK-FPC, 내압 방폭형",
      icon: "🎚️",
      price: 187000,
      image: "/images/equipment/pressure-switch-5.jpg",
      abilityUnit: null,
    },
  ],
  유수검지스위치: [
    {
      id: "flow-switch-1",
      name: "알람스위치A [우당] (프리액션스위치)",
      description: "알람스위치A(우당), 프리액션스위치 10mm/8mm",
      icon: "💦",
      price: 40700,
      image: "/images/equipment/flow-switch-1.jpg",
      abilityUnit: null,
    },
    {
      id: "flow-switch-2",
      name: "알람스위치 SAS-71N [세코스]",
      description: "알람스위치 SAS-71N[세코스], ABS카바",
      icon: "💦",
      price: 62700,
      image: "/images/equipment/flow-switch-2.jpg",
      abilityUnit: null,
    },
    {
      id: "flow-switch-3",
      name: "알람스위치 HSA-077 [파라텍]",
      description: "알람스위치 HSA-077[파라텍]",
      icon: "💦",
      price: 17600,
      image: "/images/equipment/flow-switch-3.jpg",
      abilityUnit: null,
    },
    {
      id: "flow-switch-4",
      name: "프리액션스위치 SAS-71N [숭의]",
      description: "프리액션스위치 SAS-71N[숭의], ABS카바",
      icon: "💦",
      price: 62700,
      image: "/images/equipment/flow-switch-4.jpg",
      abilityUnit: null,
    },
    {
      id: "flow-switch-5",
      name: "알람스위치 AS-2 (알람밸브용)",
      description: "알람스위치 AS-2, 알람밸브용",
      icon: "💦",
      price: 34100,
      image: "/images/equipment/flow-switch-5.jpg",
      abilityUnit: null,
    },
    {
      id: "flow-switch-6",
      name: "패들형 알람스위치 A3 [우당]",
      description: "패들형 알람스위치 A3, 우당 알람밸브 적용",
      icon: "💦",
      price: 40700,
      image: "/images/equipment/flow-switch-6.jpg",
      abilityUnit: null,
    },
    {
      id: "flow-switch-7",
      name: "알람스위치FES (알람밸브용)",
      description: "알람스위치FES, 알람밸브용 스위치",
      icon: "💦",
      price: 32000,
      image: "/images/equipment/flow-switch-7.jpg",
      abilityUnit: null,
    },
  ],
  댐퍼: [
    {
      id: "damper-1",
      name: "배연댐퍼모터 HY-24NS",
      description: "배연댐퍼모터 HY-24NS, 수동조작함 포함",
      icon: "🌀",
      price: 101200,
      image: "/images/equipment/damper-1.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-2",
      name: "배연댐퍼모터 HY-24-3000S",
      description: "배연댐퍼모터 HY-24-3000S, 수동조작함 포함",
      icon: "🌀",
      price: 75900,
      image: "/images/equipment/damper-2.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-3",
      name: "배연댐퍼모터 HY-SP (220V)",
      description: "배연댐퍼모터 HY-SP(220V), 스프링리턴타입",
      icon: "🌀",
      price: 247500,
      image: "/images/equipment/damper-3.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-4",
      name: "배기댐퍼모터 MK-DFL-60D",
      description: "배기댐퍼모터 MK-DFL-60D, 수동조작함 일체형",
      icon: "🌀",
      price: 143000,
      image: "/images/equipment/damper-4.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-5",
      name: "공조·제연겸용댐퍼모터 HY-24SI",
      description: "공조·제연겸용댐퍼모터 HY-24SI, 소방/공조 닥트 겸용",
      icon: "🌀",
      price: 115500,
      image: "/images/equipment/damper-5.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-6",
      name: "급기댐퍼모터 HM-100A",
      description: "급기댐퍼모터 HM-100A, 콘트롤박스 포함",
      icon: "🌀",
      price: 70600,
      image: "/images/equipment/damper-6.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-7",
      name: "급기댐퍼모터 MK-DFL-60L (상향식)",
      description: "급기댐퍼모터 MK-DFL-60L, 상향식 400x800",
      icon: "🌀",
      price: 170000,
      image: "/images/equipment/damper-7.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-8",
      name: "급기배기 일체형 자동차압댐퍼모터",
      description: "급기배기 일체형 자동차압댐퍼모터 MK-DFL-60LS/RS",
      icon: "🌀",
      price: 230000,
      image: "/images/equipment/damper-8.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-9",
      name: "급기댐퍼모터 MK-DFL-60R (하향식)",
      description: "급기댐퍼모터 MK-DFL-60R, 하향식(6pin)",
      icon: "🌀",
      price: 169500,
      image: "/images/equipment/damper-9.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-10",
      name: "급기댐퍼콘트롤러 MK-DFL-60S",
      description: "급기댐퍼콘트롤러 MK-DFL-60S",
      icon: "🌀",
      price: 60000,
      image: "/images/equipment/damper-10.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-11",
      name: "급기댐퍼+수동조작함 SET",
      description: "급기댐퍼+수동조작함 SET, MD-AD-202/103",
      icon: "🌀",
      price: 237000,
      image: "/images/equipment/damper-11.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-12",
      name: "차압댐퍼모터 MJC-SD-1020",
      description: "차압댐퍼모터, PCB판넬 MJC-SD-1020 계열",
      icon: "🌀",
      price: 99000,
      image: "/images/equipment/damper-12.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-13",
      name: "급기댐퍼모터 MJC-SD-1050",
      description: "급기댐퍼모터 MJC-SD-1050/1040",
      icon: "🌀",
      price: 104500,
      image: "/images/equipment/damper-13.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-14",
      name: "급기댐퍼모터(일체형구형) D1",
      description: "급기댐퍼모터(일체형구형) D1, 차압/과압 자동조절",
      icon: "🌀",
      price: 187000,
      image: "/images/equipment/damper-14.jpg",
      abilityUnit: null,
    },
    {
      id: "damper-15",
      name: "급기댐퍼모터(2) 자동차압조절기",
      description: "급기댐퍼모터(2), 자동차압조절기 분리형/일체형",
      icon: "🌀",
      price: 260000,
      image: "/images/equipment/damper-15.jpg",
      abilityUnit: null,
    },
  ],
  자동폐쇄장치: [
    {
      id: "auto-closer-1",
      name: "자동폐쇄장치 EP1400",
      description: "자동폐쇄장치 EP1400, 방화문/큰문용 KFI검정품",
      icon: "🔐",
      price: 140800,
      image: "/images/equipment/auto-closer-1.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-2",
      name: "자동폐쇄장치 DA-S-3630B (배터리식)",
      description: "자동폐쇄장치 DA-S-3630B, 감지기 일체형 배터리식",
      icon: "🔐",
      price: 286000,
      image: "/images/equipment/auto-closer-2.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-3",
      name: "자동폐쇄장치 DA-S-3630 (수신기연동형)",
      description: "자동폐쇄장치 DA-S-3630, 수신기연동형(24V)",
      icon: "🔐",
      price: 115500,
      image: "/images/equipment/auto-closer-3.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-4",
      name: "자동폐쇄장치S 매립형A",
      description: "자동폐쇄장치S 매립형A, 도어릴리즈 연동",
      icon: "🔐",
      price: 346500,
      image: "/images/equipment/auto-closer-4.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-5",
      name: "자동폐쇄장치 DA-S-3730 (큰문용)",
      description: "자동폐쇄장치 DA-S-3730, 큰문 설치가능 수신기연동형",
      icon: "🔐",
      price: 187000,
      image: "/images/equipment/auto-closer-5.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-6",
      name: "자동폐쇄장치 EP-3500",
      description: "자동폐쇄장치 EP-3500, 방화문잠금장치(프레임 밑)",
      icon: "🔐",
      price: 91300,
      image: "/images/equipment/auto-closer-6.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-7",
      name: "자동폐쇄장치 EP-2000",
      description: "자동폐쇄장치 EP-2000, 방화문잠금장치(프레임 밑)",
      icon: "🔐",
      price: 115500,
      image: "/images/equipment/auto-closer-7.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-8",
      name: "도어릴리즈 (고리식K-200)",
      description: "도어릴리즈(고리식K-200), 방화문폐쇄장치",
      icon: "🔐",
      price: 51150,
      image: "/images/equipment/auto-closer-8.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-9",
      name: "도어릴리즈 (자석식K-100)",
      description: "도어릴리즈(자석식K-100), 방화문폐쇄장치",
      icon: "🔐",
      price: 57200,
      image: "/images/equipment/auto-closer-9.jpg",
      abilityUnit: null,
    },
    {
      id: "auto-closer-10",
      name: "도어릴리즈H (고리식)",
      description: "도어릴리즈H(고리식), KFI소방검정품",
      icon: "🔐",
      price: 230000,
      image: "/images/equipment/auto-closer-10.jpg",
      abilityUnit: null,
    },
  ],
  예비펌프: [
    {
      id: "standby-pump-1",
      name: "예비펌프 5마력",
      description: "주펌프 고장 시 자동 기동하는 소용량 예비펌프",
      icon: "🔄",
      price: 1650000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "standby-pump-2",
      name: "예비펌프 10마력",
      description: "중형 건물에 적용하는 예비펌프",
      icon: "🔄",
      price: 2450000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "standby-pump-3",
      name: "예비펌프 15마력",
      description: "대형 건물 및 고층 건물에 적용하는 예비펌프",
      icon: "🔄",
      price: 3200000,
      image: null,
      abilityUnit: null,
    },
  ],
  주펌프: [
    {
      id: "main-pump-1",
      name: "주펌프 10마력",
      description: "소규모 건물에 적용하는 전동기 직결형 주펌프",
      icon: "⚙️",
      price: 2800000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "main-pump-2",
      name: "주펌프 20마력",
      description: "중형 건물에 적용하는 표준형 주펌프",
      icon: "⚙️",
      price: 4100000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "main-pump-3",
      name: "주펌프 30마력",
      description: "대형 건물 및 고층 건물에 적용하는 고용량 주펌프",
      icon: "⚙️",
      price: 5600000,
      image: null,
      abilityUnit: null,
    },
  ],
  충압펌프: [
    {
      id: "jockey-pump-1",
      name: "충압펌프 1마력",
      description: "소규모 배관 계통의 압력을 유지하는 소용량 충압펌프",
      icon: "🚰",
      price: 580000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "jockey-pump-2",
      name: "충압펌프 2마력",
      description: "배관 내 압력 저하를 자동으로 보충하는 표준형 충압펌프",
      icon: "🚰",
      price: 720000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "jockey-pump-3",
      name: "충압펌프 3마력",
      description: "대형 배관 계통에 적용하는 고용량 충압펌프",
      icon: "🚰",
      price: 890000,
      image: null,
      abilityUnit: null,
    },
  ],
  급기팬: [
    {
      id: "supply-fan-1",
      name: "FB(BTS)-500 벽걸이형 급기팬",
      description: "축사·공장용 벽걸이형 강풍기, FB(BTS)-500",
      icon: "🌬️",
      price: 196000,
      image: null,
      abilityUnit: null,
    },
    {
      id: "supply-fan-2",
      name: "FB(BTS)-600 스탠드형 급기팬",
      description: "축사·공장용 스탠드형 강풍기, FB(BTS)-600",
      icon: "🌬️",
      price: 221900,
      image: null,
      abilityUnit: null,
    },
    {
      id: "supply-fan-3",
      name: "FB(BTS)-750 벽걸이형 급기팬",
      description: "축사·공장용 벽걸이형 강풍기, FB(BTS)-750",
      icon: "🌬️",
      price: 212200,
      image: null,
      abilityUnit: null,
    },
    {
      id: "supply-fan-4",
      name: "산업용 급기팬 (공기공급 환기장비)",
      description: "산업용 급기팬, 공기 공급 환기 장비",
      icon: "🌬️",
      price: 58520,
      image: null,
      abilityUnit: null,
    },
    {
      id: "supply-fan-5",
      name: "방폭형 강풍기 급기팬 (현장용)",
      description: "방폭선풍기 겸용 강풍기 급기팬, 공사현장용",
      icon: "🌬️",
      price: 217500,
      image: null,
      abilityUnit: null,
    },
  ],
  배기팬: [
    {
      id: "exhaust-fan-1",
      name: "공업용 저소음 배기팬 (모델 1000-380)",
      description: "공업용 환풍기 겸용 저소음 배기팬, 모델 1000-380",
      icon: "🌫️",
      price: 149500,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exhaust-fan-2",
      name: "산업용 원심송풍기 배기팬 (전기블로워)",
      description: "공장환풍용 산업용 원심송풍기 배기팬, 1파이 전기블로워",
      icon: "🌫️",
      price: 271510,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exhaust-fan-3",
      name: "시로코팬 공업용 배기팬",
      description: "저소음 시로코팬 방식 소형 공업용 배기팬, 덕트모터",
      icon: "🌫️",
      price: 49330,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exhaust-fan-4",
      name: "휴대용 배기팬 (공사현장용)",
      description: "휴대용 환풍기 겸용 배기팬, 공사현장·산업용",
      icon: "🌫️",
      price: 141210,
      image: null,
      abilityUnit: null,
    },
    {
      id: "exhaust-fan-5",
      name: "덕트형 포터블 배기팬",
      description: "배풍기 겸용 포터블 배기팬, 덕트팬 업소용",
      icon: "🌫️",
      price: 82460,
      image: null,
      abilityUnit: null,
    },
  ],
};
